version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: ./backend
    container_name: backend_container
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend/app:/code/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend_container
    volumes:
      - ./frontend/app:/code/app
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local